<footer><div class="vung-bao"><div class="hang"><div class="cot-6"><a href="/" class="an-ud"><img class="chantrang-logo luoi" src="/assets/icon/bookingcare-2020.svg" data-src="/assets/icon/bookingcare-2020.svg" alt="BookingCare/" width="200" height="44"></a><div class="changtrang-congty"><h2>Công ty Cổ phần Công nghệ BookingCare</h2><p><span class="bt-g bt-g-diadiem"></span>
Lô B4/D21, Khu đô thị mới Cầu Giấy, Phường Dịch Vọng Hậu, Quận Cầu Giấy, Thành phố Hà Nội, Việt Nam
</p><p><span class="bt-g bt-g-dongy"></span>
ĐKKD số: 0106790291. Sở KHĐT Hà Nội cấp ngày 16/03/2015
</p></div><div><a class="an-ud" target="_blank" href="http://online.gov.vn/Home/WebDetails/68563"><img class="nut-bct luoi" src="/assets/icon/bo-cong-thuong.svg" data-src="/assets/icon/bo-cong-thuong.svg" alt="Đã thông báo với bộ công thương" width="78" height="30"></a><a target="_blank" href="http://online.gov.vn/Home/AppDetails/1101"><img class="nut-bct luoi" src="/assets/icon/bo-cong-thuong.svg" data-src="/assets/icon/bo-cong-thuong.svg" alt="Đã thông báo với bộ công thương" width="78" height="30"></a></div></div><div class="cot-3 an-ud"><ul><li><a href="/hop-tac-voi-bookingcare">Liên hệ hợp tác</a></li><li><a href="/danh-ba-y-te">Danh bạ y tế</a></li><li><a href="/suc-khoe-doanh-nghiep-sv10">Sức khỏe doanh nghiệp</a></li><li><a href="/goi-chuyen-doi-so">Gói chuyển đổi số doanh nghiệp</a></li><li><a href="https://tuyendung.bookingcare.vn">Tuyển dụng</a></li><li><a href="/benh-nhan-thuong-hoi">Câu hỏi thường gặp</a></li><li><a href="/page/dieu-khoan-su-dung-p7">Điều khoản sử dụng</a></li><li><a href="/page/chinh-sach-bao-mat-p8">Chính sách Bảo mật</a></li><li><a href="/thong-tin/quy-trinh-ho-tro-giai-quyet-khieu-nai-p13">Quy trình hỗ trợ giải quyết khiếu nại</a></li><li><a href="/site/quyche">Quy chế hoạt động</a></li></ul></div><div class="cot-3 an-ud"><div class="ds"><strong>Trụ sở tại Hà Nội</strong><br> Lô B4/D21, Khu đô thị mới Cầu Giấy, Phường Dịch Vọng Hậu, Quận Cầu Giấy, Thành phố Hà Nội, Việt Nam
</div><br><div class="ds"><strong>Văn phòng tại TP Hồ Chí Minh</strong><br> Số 01, Hồ Bá Kiện, Phường 15, Quận 10
</div><br><div class="ds"><strong>Hỗ trợ khách hàng</strong><br> support@bookingcare.vn (7h -
18h)
</div><br><div class="ds"><strong>Hotline</strong><br><a href="tel:02473012468">024-7301-2468</a> (7h - 18h)
</div></div></div></div><div class="vung-bao an-ud"><hr><div class="ds"><i class="bt-g bt-g-didong"></i>&nbsp;Tải ứng dụng BookingCare
cho điện thoại hoặc máy tính bảng:
<a target="_blank" href="https://bookingcare.vn/app/android">Android</a><a target="_blank" href="https://bookingcare.vn/app/ios">iPhone/iPad</a><a target="_blank" href="https://bookingcare.vn/app">Khác</a></div></div></footer>